#!/usr/bin/env bash
# =============================================================================
#  AI OS Installer — Portable Copilot Context Engine
#  Install on any repository with: bash install.sh
#  Requires: git bash, Node.js >= 20
# =============================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# ── Banner ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}  ╔═══════════════════════════════════╗${RESET}"
echo -e "${CYAN}${BOLD}  ║          AI OS  v0.2.0            ║${RESET}"
echo -e "${CYAN}${BOLD}  ║  Portable Copilot Context Engine  ║${RESET}"
echo -e "${CYAN}${BOLD}  ╚═══════════════════════════════════╝${RESET}"
echo ""

# ── Determine this script's location ─────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Determine target repo root ────────────────────────────────────────────────
TARGET_DIR=""
for arg in "$@"; do
  if [[ "$arg" == "--cwd="* ]]; then
    TARGET_DIR="${arg#--cwd=}"
  fi
done

if [[ -z "$TARGET_DIR" ]]; then
  # Default: the current working directory (where install.sh was invoked from)
  TARGET_DIR="$(pwd)"
fi

# Normalize to absolute path
TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

echo -e "  ${BOLD}Target repository:${RESET} $TARGET_DIR"
echo ""

# ── Verify it's a git repo ────────────────────────────────────────────────────
if ! git -C "$TARGET_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
  echo -e "  ${RED}✗ Not a git repository: $TARGET_DIR${RESET}"
  echo -e "  ${YELLOW}  Run 'git init' first, or cd into a git repository.${RESET}"
  exit 1
fi

echo -e "  ${GREEN}✓ Git repository detected${RESET}"

# ── Check Node.js version ────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo -e "  ${RED}✗ Node.js not found.${RESET}"
  echo -e "  ${YELLOW}  Please install Node.js >= 20 from https://nodejs.org${RESET}"
  exit 1
fi

NODE_VERSION=$(node --version | sed 's/v//')
NODE_MAJOR=$(echo "$NODE_VERSION" | cut -d. -f1)

if [[ "$NODE_MAJOR" -lt 20 ]]; then
  echo -e "  ${RED}✗ Node.js $NODE_VERSION is too old. Need >= 20.${RESET}"
  echo -e "  ${YELLOW}  Update Node.js at https://nodejs.org${RESET}"
  exit 1
fi

echo -e "  ${GREEN}✓ Node.js v$NODE_VERSION${RESET}"

# ── Check npm ────────────────────────────────────────────────────────────────
if ! command -v npm &>/dev/null; then
  echo -e "  ${RED}✗ npm not found. Install Node.js from https://nodejs.org${RESET}"
  exit 1
fi

echo -e "  ${GREEN}✓ npm $(npm --version)${RESET}"
echo ""

# ── Locate ai-os source ───────────────────────────────────────────────────────
AIOS_SRC="$SCRIPT_DIR"
if [[ ! -f "$AIOS_SRC/package.json" ]]; then
  echo -e "  ${RED}✗ Cannot find ai-os package at: $AIOS_SRC${RESET}"
  exit 1
fi

# ── Install ai-os dependencies (into scripts/ai-os/node_modules) ─────────────
echo -e "  ${CYAN}→ Installing dependencies...${RESET}"
(cd "$AIOS_SRC" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -3)
echo -e "  ${GREEN}✓ Dependencies ready${RESET}"
echo ""

# ── Compile TypeScript (if dist/ is stale or missing) ────────────────────────
GENERATE_SCRIPT="$AIOS_SRC/src/generate.ts"
if [[ ! -f "$GENERATE_SCRIPT" ]]; then
  echo -e "  ${RED}✗ generate.ts not found at: $GENERATE_SCRIPT${RESET}"
  exit 1
fi

# ── Run the generator ────────────────────────────────────────────────────────
echo -e "  ${CYAN}→ Scanning codebase and generating context...${RESET}"
echo ""

(cd "$AIOS_SRC" && node --import tsx/esm src/generate.ts --cwd "$TARGET_DIR")

# ── Copy MCP server to target repo ──────────────────────────────────────────
MCP_SERVER_SRC="$AIOS_SRC/src/mcp-server"
MCP_SERVER_DEST="$TARGET_DIR/.ai-os/mcp-server"

mkdir -p "$MCP_SERVER_DEST"

echo -e "  ${CYAN}→ Installing MCP server to .ai-os/mcp-server/...${RESET}"

# Copy MCP server source files
cp -r "$MCP_SERVER_SRC"/* "$MCP_SERVER_DEST/"

# Create a minimal package.json for the MCP server in the target repo
cat > "$MCP_SERVER_DEST/package.json" << 'EOF'
{
  "name": "ai-os-mcp-server",
  "version": "0.1.0",
  "type": "module",
  "main": "index.js",
  "dependencies": {
    "@github/copilot-sdk": "^0.1.8"
  }
}
EOF

# Install MCP server dependencies
(cd "$MCP_SERVER_DEST" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -3)

# Transpile MCP server for runtime (inline using tsx)
cat > "$MCP_SERVER_DEST/index.js" << 'EOF'
#!/usr/bin/env node
// AI OS MCP Server — auto-generated entry point
// This file is generated by ai-os install. Do not edit manually.
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const path = require('path');
const { execFileSync } = require('child_process');

const tsxBin = path.join(path.dirname(new URL(import.meta.url).pathname), 'node_modules', '.bin', 'tsx');
const indexTs = path.join(path.dirname(new URL(import.meta.url).pathname), 'index.ts');

// Try to run via tsx (TypeScript)
try {
  execFileSync(process.execPath, ['--import', 'tsx/esm', indexTs], {
    stdio: 'inherit',
    env: { ...process.env, AI_OS_ROOT: process.env.AI_OS_ROOT ?? process.cwd() },
  });
} catch {
  process.exit(1);
}
EOF

echo -e "  ${GREEN}✓ MCP server installed${RESET}"
echo ""

# ── Add .ai-os to .gitignore (optional) ───────────────────────────────────────
GITIGNORE="$TARGET_DIR/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
  if ! grep -q "^\.ai-os/node_modules" "$GITIGNORE" 2>/dev/null; then
    echo "" >> "$GITIGNORE"
    echo "# AI OS (generated — safe to commit except node_modules)" >> "$GITIGNORE"
    echo ".ai-os/mcp-server/node_modules" >> "$GITIGNORE"
    echo -e "  ${GREEN}✓ Updated .gitignore${RESET}"
  fi
fi

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}${BOLD}✅ AI OS installed successfully!${RESET}"
echo ""
echo -e "  ${BOLD}Next steps:${RESET}"
echo -e "  1. Open this repo in VS Code with GitHub Copilot extension installed"
echo -e "  2. Copilot will use ${CYAN}.github/copilot-instructions.md${RESET} automatically"
echo -e "  3. MCP tools are registered in ${CYAN}.github/copilot/mcp.json${RESET}"
echo -e "  4. Project context is in ${CYAN}.ai-os/context/${RESET}"
echo ""
echo -e "  ${YELLOW}Tip:${RESET} Re-run install.sh anytime to refresh context after major refactors."
echo ""
