import fs from 'node:fs';
import path from 'node:path';
import type { DetectedStack, AiOsConfig } from '../types.js';
import { writeIfChanged } from './utils.js';

interface GenerateCloudAgentOptions {
  config?: AiOsConfig;
}

const OUTPUT_FILE = path.join('.github', 'copilot-setup-steps.yml');

/**
 * Generates `.github/copilot-setup-steps.yml` for Copilot Cloud Agent.
 *
 * This file tells the Copilot coding agent how to pre-configure the
 * environment before running any coding task. The generated steps are
 * derived from the detected tech stack so the environment matches the
 * local development setup.
 *
 * Enabled by setting `"cloudAgent": true` in `.github/ai-os/config.json`.
 * Default: false (opt-in).
 *
 * Documentation:
 *   https://docs.github.com/en/copilot/how-tos/use-copilot-agents/copilot-setup-steps
 */
export function generateCloudAgent(
  outputDir: string,
  stack: DetectedStack,
  options?: GenerateCloudAgentOptions,
): string[] {
  if (!options?.config?.cloudAgent) return [];

  const filePath = path.join(outputDir, OUTPUT_FILE);
  writeIfChanged(filePath, buildYaml(stack));
  return [filePath];
}

function buildYaml(stack: DetectedStack): string {
  const lines: string[] = [
    '# .github/copilot-setup-steps.yml',
    '# Generated by AI OS. Do not edit manually; managed via .github/ai-os/config.json.',
    '#',
    '# Copilot Cloud Agent uses these steps to pre-configure the environment',
    '# before executing any coding task in this repository.',
    '#',
    '# Documentation: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/copilot-setup-steps',
    '',
    'steps:',
  ];

  const pm = stack.patterns.packageManager;
  const lang = stack.primaryLanguage.name.toLowerCase();

  if (pm === 'npm' || pm === 'yarn' || pm === 'pnpm' || pm === 'bun') {
    lines.push(...buildNodeSteps(pm, stack));
  } else if (pm === 'pip' || pm === 'poetry' || lang === 'python') {
    lines.push(...buildPythonSteps(pm, stack));
  } else if (pm === 'go' || lang === 'go') {
    lines.push(...buildGoSteps(stack));
  } else if (pm === 'cargo' || lang === 'rust') {
    lines.push(...buildRustSteps());
  } else if (pm === 'maven' || pm === 'gradle' || lang === 'java' || lang === 'kotlin') {
    lines.push(...buildJavaSteps(pm));
  } else if (pm === 'dotnet' || lang === 'c#' || lang === 'f#') {
    lines.push(...buildDotnetSteps());
  } else {
    // Unknown stack — emit a placeholder that is still valid YAML
    lines.push(...buildFallbackSteps());
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Per-stack step builders
// ---------------------------------------------------------------------------

function buildNodeSteps(pm: string, stack: DetectedStack): string[] {
  const nodeVersion = detectNodeVersion(stack) ?? '20';
  const installCmd = pm === 'yarn' ? 'yarn install --frozen-lockfile'
    : pm === 'pnpm' ? 'pnpm install --frozen-lockfile'
    : pm === 'bun' ? 'bun install'
    : 'npm ci';

  const setupSteps: string[] = [
    `  - name: Set up Node.js`,
    `    uses: actions/setup-node@v4`,
    `    with:`,
    `      node-version: '${nodeVersion}'`,
  ];

  if (pm === 'npm' || pm === 'yarn' || pm === 'pnpm') {
    setupSteps.push(`      cache: '${pm}'`);
  }

  if (pm === 'pnpm') {
    // pnpm must be installed before setup-node cache works
    setupSteps.unshift(
      `  - name: Install pnpm`,
      `    uses: pnpm/action-setup@v4`,
      `    with:`,
      `      version: latest`,
    );
  }

  setupSteps.push(
    ``,
    `  - name: Install dependencies`,
    `    run: ${installCmd}`,
  );

  return setupSteps;
}

function buildPythonSteps(pm: string, stack: DetectedStack): string[] {
  const pyVersion = detectPythonVersion(stack) ?? '3.12';
  const installCmd = pm === 'poetry'
    ? 'poetry install --no-interaction'
    : 'pip install -r requirements.txt';

  const steps: string[] = [
    `  - name: Set up Python`,
    `    uses: actions/setup-python@v5`,
    `    with:`,
    `      python-version: '${pyVersion}'`,
    `      cache: 'pip'`,
    ``,
    `  - name: Install dependencies`,
    `    run: ${installCmd}`,
  ];

  if (pm === 'poetry') {
    steps.unshift(
      `  - name: Install Poetry`,
      `    uses: snok/install-poetry@v1`,
      ``,
    );
  }

  return steps;
}

function buildGoSteps(stack: DetectedStack): string[] {
  const goVersion = detectGoVersion(stack) ?? '1.22';
  return [
    `  - name: Set up Go`,
    `    uses: actions/setup-go@v5`,
    `    with:`,
    `      go-version: '${goVersion}'`,
    `      cache: true`,
    ``,
    `  - name: Download Go modules`,
    `    run: go mod download`,
  ];
}

function buildRustSteps(): string[] {
  return [
    `  - name: Set up Rust`,
    `    uses: dtolnay/rust-toolchain@stable`,
    ``,
    `  - name: Cache Cargo`,
    `    uses: Swatinem/rust-cache@v2`,
  ];
}

function buildJavaSteps(pm: string): string[] {
  const buildCmd = pm === 'gradle' ? './gradlew dependencies' : 'mvn dependency:resolve -q';
  return [
    `  - name: Set up Java`,
    `    uses: actions/setup-java@v4`,
    `    with:`,
    `      distribution: 'temurin'`,
    `      java-version: '21'`,
    `      cache: '${pm === 'gradle' ? 'gradle' : 'maven'}'`,
    ``,
    `  - name: Resolve dependencies`,
    `    run: ${buildCmd}`,
  ];
}

function buildDotnetSteps(): string[] {
  return [
    `  - name: Set up .NET`,
    `    uses: actions/setup-dotnet@v4`,
    `    with:`,
    `      dotnet-version: '8.x'`,
    ``,
    `  - name: Restore NuGet packages`,
    `    run: dotnet restore`,
  ];
}

function buildFallbackSteps(): string[] {
  return [
    `  # AI OS could not detect the project stack.`,
    `  # Add the appropriate setup steps for your language/runtime here.`,
    `  # See: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/copilot-setup-steps`,
    `  - name: Setup environment`,
    `    run: echo "Add project-specific setup steps here"`,
  ];
}

// ---------------------------------------------------------------------------
// Version sniffing helpers (best-effort; fall back to safe defaults)
// ---------------------------------------------------------------------------

function detectNodeVersion(stack: DetectedStack): string | undefined {
  // Try .nvmrc / .node-version via keyFiles hint (files must exist in repo)
  if (stack.keyFiles.some(f => f.includes('.nvmrc') || f.includes('.node-version'))) {
    // We can't read the file here without the rootDir, so return undefined and
    // let the caller fall back to the default.
    return undefined;
  }

  // Check engines.node in package.json dependencies list (not available in stack)
  // or try to infer from framework versions
  const deps = stack.allDependencies;
  if (deps.includes('next') || deps.includes('react')) return '20';
  return undefined;
}

function detectPythonVersion(stack: DetectedStack): string | undefined {
  const deps = stack.allDependencies;
  // django 5+ requires Python 3.10+
  if (deps.includes('django')) return '3.12';
  return undefined;
}

function detectGoVersion(stack: DetectedStack): string | undefined {
  // go.mod is a keyFile — read it for `go 1.x` directive
  const goMod = stack.keyFiles.find(f => f === 'go.mod');
  if (!goMod) return undefined;
  try {
    const content = fs.readFileSync(path.join(stack.rootDir, 'go.mod'), 'utf-8');
    const m = content.match(/^go\s+(\d+\.\d+)/m);
    if (m) return m[1];
  } catch { /* ignore */ }
  return undefined;
}
