import fs from 'node:fs';
import path from 'node:path';
import type { DetectedStack } from '../types.js';

function generateStackDoc(stack: DetectedStack): string {
  const lines: string[] = [
    `# Tech Stack — ${stack.projectName}`,
    '',
    '## Languages',
    '',
  ];

  for (const lang of stack.languages) {
    lines.push(`- **${lang.name}** — ${lang.fileCount} files (${lang.percentage}%) | extensions: ${lang.extensions.map(e => `.${e}`).join(', ')}`);
  }

  lines.push('', '## Frameworks & Libraries', '');
  if (stack.frameworks.length === 0) {
    lines.push(`- ${stack.primaryLanguage.name} (no framework detected)`);
  } else {
    for (const fw of stack.frameworks) {
      const version = fw.version ? ` v${fw.version}` : '';
      lines.push(`- **${fw.name}**${version} (${fw.category})`);
    }
  }

  lines.push('', '## Build & Tooling', '');
  lines.push(`- **Package Manager:** ${stack.patterns.packageManager}`);
  if (stack.patterns.bundler) lines.push(`- **Bundler:** ${stack.patterns.bundler}`);
  if (stack.patterns.linter) lines.push(`- **Linter:** ${stack.patterns.linter}`);
  if (stack.patterns.formatter) lines.push(`- **Formatter:** ${stack.patterns.formatter}`);
  if (stack.patterns.testFramework) lines.push(`- **Test Framework:** ${stack.patterns.testFramework}`);
  if (stack.patterns.ciCdProvider) lines.push(`- **CI/CD:** ${stack.patterns.ciCdProvider}`);
  lines.push(`- **TypeScript:** ${stack.patterns.hasTypeScript ? 'Yes' : 'No'}`);
  lines.push(`- **Docker:** ${stack.patterns.hasDockerfile ? 'Yes' : 'No'}`);
  lines.push(`- **Monorepo:** ${stack.patterns.monorepo ? 'Yes' : 'No'}`);

  lines.push('', '## Key Files', '');
  for (const f of stack.keyFiles) {
    lines.push(`- \`${f}\``);
  }

  return lines.join('\n');
}

function generateArchitectureDoc(stack: DetectedStack): string {
  const lines: string[] = [
    `# Architecture — ${stack.projectName}`,
    '',
    '> Auto-generated by AI OS. Update this file as the architecture evolves.',
    '',
    '## Project Type',
    '',
  ];

  const fw = stack.primaryFramework;
  if (fw) {
    lines.push(`**${fw.name}** (${fw.category}) project.`);
  } else {
    lines.push(`**${stack.primaryLanguage.name}** project.`);
  }

  lines.push('', '## Directory Structure', '');
  lines.push('```');
  try {
    const entries = fs.readdirSync(stack.rootDir).filter(e => !e.startsWith('.') && e !== 'node_modules');
    for (const entry of entries.slice(0, 20)) {
      const stat = fs.statSync(path.join(stack.rootDir, entry));
      lines.push(stat.isDirectory() ? `${entry}/` : entry);
    }
  } catch {
    lines.push('(could not read directory)');
  }
  lines.push('```');

  lines.push('', '## Data Flow', '');
  if (fw?.name === 'Next.js') {
    lines.push('```');
    lines.push('Browser → Next.js App Router → Server Components → DB/API');
    lines.push('       ↘ Client Components → tRPC/fetch → API Routes → DB');
    lines.push('```');
  } else if (fw?.category === 'backend') {
    lines.push('```');
    lines.push('Client → HTTP/REST → Controller → Service → Database');
    lines.push('```');
  } else if (fw?.category === 'fullstack') {
    lines.push('```');
    lines.push('Browser → Routes/Pages → Server Logic → Database/API');
    lines.push('```');
  } else {
    lines.push('_Update this section with your actual data flow._');
  }

  lines.push('', '## Integration Points', '');
  lines.push('_List external services, APIs, and third-party integrations here._');

  return lines.join('\n');
}

function generateConventionsDoc(stack: DetectedStack): string {
  const lines: string[] = [
    `# Coding Conventions — ${stack.projectName}`,
    '',
    '> Auto-generated by AI OS. Update to reflect actual team agreements.',
    '',
    '## Naming Conventions',
    '',
    `- **General style:** ${stack.patterns.namingConvention}`,
  ];

  if (stack.patterns.hasTypeScript) {
    lines.push('- **TypeScript interfaces:** PascalCase (e.g., `UserProfile`)');
    lines.push('- **Types/Enums:** PascalCase');
    lines.push('- **Variables/functions:** camelCase');
    lines.push('- **Constants:** SCREAMING_SNAKE_CASE');
  }

  if (stack.primaryFramework?.name === 'Next.js' || stack.primaryFramework?.name === 'React') {
    lines.push('- **React components:** PascalCase files + exports');
    lines.push('- **Hooks:** `use` prefix (e.g., `useAuth`, `useCart`)');
    lines.push('- **Event handlers:** `handle` prefix (e.g., `handleSubmit`)');
    lines.push('- **Boolean state:** `is`/`has`/`show` prefix (e.g., `isLoading`, `hasError`)');
  }

  lines.push('', '## File Structure Rules', '');
  if (stack.patterns.srcDirectory) {
    lines.push('- All source code lives under `src/`');
  }
  if (stack.patterns.testDirectory) {
    lines.push(`- Tests in \`${stack.patterns.testDirectory}/\``);
  }
  if (stack.patterns.linter) {
    lines.push(`- Linter: **${stack.patterns.linter}** — must pass before committing`);
  }
  if (stack.patterns.formatter) {
    lines.push(`- Formatter: **${stack.patterns.formatter}** — auto-format on save`);
  }

  lines.push('', '## Code Style', '');
  lines.push('- Prefer early returns over deep nesting');
  lines.push('- Validate all external inputs at API/form boundaries');
  lines.push('- Async/await over .then() chains');
  lines.push('- No commented-out code in commits');
  lines.push('- No secrets or credentials in source code');

  if (stack.patterns.testFramework) {
    lines.push('', '## Testing', '');
    lines.push(`- Framework: **${stack.patterns.testFramework}**`);
    lines.push('- Unit tests for all business logic');
    lines.push('- Integration tests for API endpoints');
    lines.push('- Never hit real external services in unit tests — mock them');
  }

  return lines.join('\n');
}

export function generateContextDocs(stack: DetectedStack, outputDir: string): void {
  const contextDir = path.join(outputDir, '.ai-os', 'context');
  fs.mkdirSync(contextDir, { recursive: true });

  fs.writeFileSync(path.join(contextDir, 'stack.md'), generateStackDoc(stack), 'utf-8');
  fs.writeFileSync(path.join(contextDir, 'architecture.md'), generateArchitectureDoc(stack), 'utf-8');
  fs.writeFileSync(path.join(contextDir, 'conventions.md'), generateConventionsDoc(stack), 'utf-8');

  // Write config.json
  const config = {
    version: '0.1.0',
    installedAt: new Date().toISOString(),
    projectName: stack.projectName,
    primaryLanguage: stack.primaryLanguage.name,
    primaryFramework: stack.primaryFramework?.name ?? null,
    frameworks: stack.frameworks.map(f => f.name),
    packageManager: stack.patterns.packageManager,
    hasTypeScript: stack.patterns.hasTypeScript,
  };

  const aiOsDir = path.join(outputDir, '.ai-os');
  fs.writeFileSync(path.join(aiOsDir, 'config.json'), JSON.stringify(config, null, 2), 'utf-8');
}
