import path from 'node:path';
import type { AiOsConfig } from '../types.js';
import { writeIfChanged } from './utils.js';

interface GenerateHooksOptions {
  config?: AiOsConfig;
}

/**
 * Generates opt-in git hook scripts in .githooks/.
 *
 * Enabled by setting "gitHooks": true in .github/ai-os/config.json.
 *
 * To activate after generation, run once in the target repo:
 *   git config core.hooksPath .githooks
 *
 * The pre-push hook emits a non-blocking drift warning if AI OS context
 * has fallen out of sync with the codebase.
 */
export function generateHooks(outputDir: string, options?: GenerateHooksOptions): string[] {
  if (!options?.config?.gitHooks) return [];

  const managed: string[] = [];
  const track = (p: string): string => {
    managed.push(p);
    return p;
  };

  const prePushPath = track(path.join(outputDir, '.githooks', 'pre-push'));
  writeIfChanged(prePushPath, getPrePushHookContent());

  return managed;
}

function getPrePushHookContent(): string {
  return `#!/usr/bin/env bash
# AI OS pre-push hook — drift warning (non-blocking).
# Generated by AI OS. Do not edit manually; managed via .github/ai-os/config.json.
#
# To activate: git config core.hooksPath .githooks
# To disable:  set "gitHooks": false in .github/ai-os/config.json and re-run AI OS.

set -euo pipefail

# Require node; skip hook gracefully if not available.
if ! command -v node &>/dev/null; then
  exit 0
fi

# Resolve the AI OS generate script (bundle takes priority over npx for speed).
BUNDLE=".ai-os/mcp-server/generate.js"

if [ -f "$BUNDLE" ]; then
  DRIFT=$(node "$BUNDLE" --check-drift --json 2>/dev/null | node -e "
    let d=''; process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=>{
      try { const r=JSON.parse(d); process.stdout.write(r.driftDetected?'1':'0'); }
      catch { process.stdout.write('0'); }
    });" 2>/dev/null || echo "0")
else
  # Fall back to npx (slower but works without a local bundle).
  DRIFT=$(npx -y "github:marinvch/ai-os" --check-drift --json 2>/dev/null | node -e "
    let d=''; process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=>{
      try { const r=JSON.parse(d); process.stdout.write(r.driftDetected?'1':'0'); }
      catch { process.stdout.write('0'); }
    });" 2>/dev/null || echo "0")
fi

if [ "$DRIFT" = "1" ]; then
  echo ""
  echo "  ⚠️  AI OS drift detected — your Copilot context may be stale."
  echo "  Run to refresh:  npx -y github:marinvch/ai-os --refresh-existing"
  echo ""
fi

# Non-blocking — always exit 0 so the push proceeds.
exit 0
`;
}
