/**
 * multi-editor.ts — Generate AI instruction configs for non-VS Code editors.
 *
 * Supported targets:
 * - cursor: .cursorrules (project root)
 * - jetbrains: .github/ai-os/jetbrains-ai-context.md (loaded via AI Assistant plugin)
 * - neovim: .github/ai-os/nvim-context.md (loaded by Avante/CodeCompanion/CopilotChat)
 */
import fs from 'node:fs';
import path from 'node:path';
import type { DetectedStack } from '../types.js';
import { writeIfChanged } from './utils.js';

export type EditorTarget = 'vscode' | 'cursor' | 'jetbrains' | 'neovim' | 'all';

export function parseEditorTarget(raw: string): EditorTarget | null {
  const targets: EditorTarget[] = ['vscode', 'cursor', 'jetbrains', 'neovim', 'all'];
  const lower = raw.toLowerCase() as EditorTarget;
  return targets.includes(lower) ? lower : null;
}

/**
 * Detect which editors appear to be in use in the project.
 * Used to auto-generate editor configs on normal --refresh-existing.
 */
export function detectEditorTargets(cwd: string): EditorTarget[] {
  const detected: EditorTarget[] = ['vscode'];
  if (fs.existsSync(path.join(cwd, '.idea'))) detected.push('jetbrains');
  if (fs.existsSync(path.join(cwd, '.cursorrules'))) detected.push('cursor');
  return detected;
}

/**
 * Generate .cursorrules from copilot-instructions.md content.
 * Cursor reads .cursorrules from the project root.
 */
export function generateCursorRules(stack: DetectedStack, instructionsContent: string): string {
  const header = [
    `# Cursor AI Rules — ${stack.projectName}`,
    `# Generated by AI OS — https://github.com/marinvch/ai-os`,
    `# Edit this file directly OR protect sections with AI-OS:USER_BLOCK markers.`,
    '',
  ].join('\n');
  // Strip the YAML front-matter comment if it exists (copilot-specific)
  const cleaned = instructionsContent.replace(/^---\napplyTo: "\*\*"\n---\n/m, '').trim();
  return `${header}\n${cleaned}\n`;
}

/**
 * Generate a JetBrains AI Assistant context file.
 * JetBrains AI Assistant v2024.3+ supports .github/copilot-instructions.md natively
 * but also reads from a project-level prompt library. We generate a companion file
 * at .github/ai-os/jetbrains-ai-context.md with structured prompts.
 */
export function generateJetBrainsContext(stack: DetectedStack): string {
  const fw = stack.primaryFramework?.name ?? stack.primaryLanguage.name;
  const pm = stack.patterns.packageManager;
  const isNode = ['npm', 'yarn', 'pnpm', 'bun'].includes(pm);
  const buildCmd = isNode
    ? `${pm} run build`
    : pm === 'go'
      ? 'go build ./...'
      : pm === 'cargo'
        ? 'cargo build'
        : 'build';
  const testCmd = isNode
    ? `${pm} run test`
    : pm === 'go'
      ? 'go test ./...'
      : pm === 'cargo'
        ? 'cargo test'
        : 'test';

  return (
    [
      `<!-- JetBrains AI Assistant Context — ${stack.projectName} -->`,
      `<!-- Generated by AI OS. Source of truth: .github/copilot-instructions.md -->`,
      '',
      `# Project: ${stack.projectName}`,
      '',
      `**Primary language:** ${stack.primaryLanguage.name}${stack.patterns.hasTypeScript ? ' (TypeScript)' : ''}  `,
      `**Framework:** ${fw}  `,
      `**Package manager:** ${pm}  `,
      '',
      '## Build & Test',
      '',
      `- Build: \`${buildCmd}\``,
      `- Test: \`${testCmd}\``,
      stack.patterns.linter
        ? `- Lint: \`${isNode ? `${pm} run lint` : stack.patterns.linter}\``
        : '',
      '',
      '## Coding Rules',
      '',
      `- Use ${fw} conventions for all new code`,
      '- Prefer early returns (guard clauses) over deep nesting',
      '- Never commit secrets or credentials',
      '- Only comment code that genuinely needs clarification',
      '- Use async/await over .then() chains',
      '',
      '## Full Instructions',
      '',
      'For the complete set of rules, refer to `.github/copilot-instructions.md`.',
      'AI OS re-generates this file on every `--refresh-existing` run.',
    ]
      .filter((line) => line !== null)
      .join('\n') + '\n'
  );
}

/**
 * Generate a Neovim AI plugin context file.
 * Loaded by Avante.nvim, CodeCompanion.nvim, CopilotChat.nvim via their
 * project-level context configuration.
 */
export function generateNeovimContext(stack: DetectedStack): string {
  const fw = stack.primaryFramework?.name ?? stack.primaryLanguage.name;
  const pm = stack.patterns.packageManager;
  const isNode = ['npm', 'yarn', 'pnpm', 'bun'].includes(pm);
  const buildCmd = isNode
    ? `${pm} run build`
    : pm === 'go'
      ? 'go build ./...'
      : pm === 'cargo'
        ? 'cargo build'
        : 'build';
  const testCmd = isNode
    ? `${pm} run test`
    : pm === 'go'
      ? 'go test ./...'
      : pm === 'cargo'
        ? 'cargo test'
        : 'test';

  return (
    [
      `# Neovim AI Context — ${stack.projectName}`,
      `# Generated by AI OS. Full rules: .github/copilot-instructions.md`,
      '',
      `Stack: ${fw} · ${stack.primaryLanguage.name}${stack.patterns.hasTypeScript ? '+TypeScript' : ''} · ${pm}`,
      `Build: ${buildCmd} | Test: ${testCmd}`,
      '',
      '## Rules',
      `- Use ${fw} conventions`,
      '- Prefer early returns over deep nesting',
      '- Async/await over .then() chains',
      '- Never commit secrets',
      '- Small focused functions with single responsibility',
      '',
      '## Key Files',
      ...stack.keyFiles.slice(0, 5).map((f) => `- ${f}`),
      '',
      `# Full context: see .github/copilot-instructions.md`,
    ].join('\n') + '\n'
  );
}

/**
 * Write all editor-specific config files for the given targets.
 * Returns a list of files written.
 */
export function generateEditorConfigs(
  cwd: string,
  stack: DetectedStack,
  targets: EditorTarget[],
  instructionsContent: string,
  track: (p: string) => string,
): string[] {
  const written: string[] = [];
  const effectiveTargets = new Set(
    targets.includes('all')
      ? (['cursor', 'jetbrains', 'neovim'] as EditorTarget[])
      : targets.filter((t) => t !== 'vscode'),
  );

  if (effectiveTargets.has('cursor')) {
    const dest = track(path.join(cwd, '.cursorrules'));
    writeIfChanged(dest, generateCursorRules(stack, instructionsContent));
    written.push('.cursorrules');
  }

  if (effectiveTargets.has('jetbrains')) {
    const aiOsDir = path.join(cwd, '.github', 'ai-os');
    if (!fs.existsSync(aiOsDir)) fs.mkdirSync(aiOsDir, { recursive: true });
    const dest = track(path.join(aiOsDir, 'jetbrains-ai-context.md'));
    writeIfChanged(dest, generateJetBrainsContext(stack));
    written.push('.github/ai-os/jetbrains-ai-context.md');
  }

  if (effectiveTargets.has('neovim')) {
    const aiOsDir = path.join(cwd, '.github', 'ai-os');
    if (!fs.existsSync(aiOsDir)) fs.mkdirSync(aiOsDir, { recursive: true });
    const dest = track(path.join(aiOsDir, 'nvim-context.md'));
    writeIfChanged(dest, generateNeovimContext(stack));
    written.push('.github/ai-os/nvim-context.md');
  }

  return written;
}
