import fs from 'node:fs';
import path from 'node:path';
import type { DetectedStack } from '../types.js';
import { writeIfChanged } from '../generators/utils.js';
import {
  DEPENDENCY_RECOMMENDATIONS,
  FRAMEWORK_RECOMMENDATIONS,
  LANGUAGE_RECOMMENDATIONS,
  UNIVERSAL_RECOMMENDATIONS,
  type StackRecommendation,
} from './registry.js';
import { buildSkillsInstallCommand } from './cli-compat.js';

interface CollectedRecommendations {
  mcp: Array<{ trigger: string; package: string; description: string }>;
  vscode: Array<{ trigger: string; id: string }>;
  skills: Array<{ trigger: string; name: string; source?: string }>;
  copilotExtensions: Array<{ trigger: string; name: string; url: string }>;
  /** Whether this entry came from a universal (always-on) recommendation */
  universalSkills: Array<{ trigger: string; name: string; source?: string }>;
  /** Plugin install steps for agent harnesses (Claude Code, GitHub Copilot CLI, Cursor, etc.) */
  pluginInstalls: Array<{ trigger: string; name: string; description: string; skillSource?: string; steps: Array<{ harness: string; command: string }> }>;
}

export function collectRecommendations(stack: DetectedStack): CollectedRecommendations {
  const collected: CollectedRecommendations = { mcp: [], vscode: [], skills: [], copilotExtensions: [], universalSkills: [], pluginInstalls: [] };
  const seenMcp = new Set<string>();
  const seenVscode = new Set<string>();
  const seenSkills = new Set<string>();
  const seenExt = new Set<string>();

  // Build a fallback source map from universal recommendations so stack-specific
  // entries with no skillSources can resolve known skills (e.g. context7).
  const universalSkillSources: Record<string, string> = {};
  for (const rec of UNIVERSAL_RECOMMENDATIONS) {
    for (const [skillName, source] of Object.entries(rec.skillSources ?? {})) {
      if (!universalSkillSources[skillName]) universalSkillSources[skillName] = source;
    }
  }

  function applyRec(rec: StackRecommendation, isUniversal = false): void {
    if (rec.mcp && !seenMcp.has(rec.mcp.package)) {
      seenMcp.add(rec.mcp.package);
      collected.mcp.push({ trigger: rec.trigger, package: rec.mcp.package, description: rec.mcp.description });
    }
    for (const ext of rec.vscode ?? []) {
      if (!seenVscode.has(ext)) {
        seenVscode.add(ext);
        collected.vscode.push({ trigger: rec.trigger, id: ext });
      }
    }
    for (const skill of rec.skills ?? []) {
      if (!seenSkills.has(skill)) {
        seenSkills.add(skill);
        const source = rec.skillSources?.[skill] ?? universalSkillSources[skill];
        if (isUniversal) {
          collected.universalSkills.push({ trigger: rec.trigger, name: skill, source });
        } else {
          collected.skills.push({ trigger: rec.trigger, name: skill, source });
        }
      }
    }
    if (rec.copilotExtension && !seenExt.has(rec.copilotExtension.name)) {
      seenExt.add(rec.copilotExtension.name);
      collected.copilotExtensions.push({ trigger: rec.trigger, ...rec.copilotExtension });
    }
    if (rec.pluginInstall && !collected.pluginInstalls.some(p => p.name === rec.pluginInstall!.name)) {
      collected.pluginInstalls.push({ trigger: rec.trigger, name: rec.pluginInstall.name, description: rec.pluginInstall.description, skillSource: rec.pluginInstall.skillSource, steps: rec.pluginInstall.steps });
    }
  }

  // Check dependencies
  for (const dep of stack.allDependencies) {
    const rec = DEPENDENCY_RECOMMENDATIONS[dep];
    if (rec) applyRec(rec);
  }

  // Check frameworks
  for (const fw of stack.frameworks) {
    const rec = FRAMEWORK_RECOMMENDATIONS[fw.name];
    if (rec) applyRec(rec);
  }

  // Check languages
  for (const lang of stack.languages) {
    const rec = LANGUAGE_RECOMMENDATIONS[lang.name];
    if (rec) applyRec(rec);
  }

  // Always apply universal recommendations (tracked separately to allow optional section)
  for (const rec of UNIVERSAL_RECOMMENDATIONS) {
    applyRec(rec, true);
  }

  return collected;
}

function generateRecommendationsDoc(stack: DetectedStack, collected: CollectedRecommendations): string {
  const lines: string[] = [
    `# AI OS Recommendations — ${stack.projectName}`,
    '',
    '> Auto-generated by AI OS based on detected stack. Refreshed on every `--refresh-existing` run.',
    '',
  ];

  lines.push('## Lifecycle Orchestration (Define → Plan → Build → Verify → Review → Ship)', '');
  lines.push('AI OS embeds slash-command prompts for each lifecycle phase. Use them in order:');
  lines.push('');
  lines.push('| Phase | Prompt | Purpose |');
  lines.push('| ----- | ------ | ------- |');
  lines.push('| Define | `/define` | Structure feature intent, scope, constraints, and success criteria |');
  lines.push('| Plan | `/plan` | Break the feature into ordered, dependency-aware implementation tasks |');
  lines.push('| Build | `/build` | Execute one task at a time with minimal, convention-compliant changes |');
  lines.push('| Verify | `/verify` | Check implementation against success criteria and run tests |');
  lines.push('| Review | `/review` | Severity-tagged code review (Critical → Required → Optional → FYI) |');
  lines.push('| Ship | `/ship` | Pre-ship checklist — tests, secrets scan, changelog, version bump |');
  lines.push('');
  lines.push('>  Use them in Copilot Chat, or map them to VS Code slash commands by adding prompt files to `.github/copilot/prompts/`.');
  lines.push('');

  if (collected.mcp.length > 0) {
    lines.push('## Recommended MCP Servers', '');
    for (const item of collected.mcp) {
      lines.push(`### ${item.package}`);
      lines.push(`> Triggered by: \`${item.trigger}\``);
      lines.push('');
      lines.push(item.description);
      lines.push('');
      lines.push('**Install in Copilot CLI `.mcp.json` under `mcpServers`:**');
      lines.push('```json');
      lines.push(`"${item.package.replace('/', '-')}": {`);
      lines.push('  "type": "stdio",');
      lines.push(`  "command": "npx",`);
      lines.push(`  "args": ["-y", "${item.package}"]`);
      lines.push('}');
      lines.push('```');
      lines.push('');
      lines.push('**Install in VS Code `.vscode/mcp.json` under `servers`:**');
      lines.push('```json');
      lines.push(`"${item.package.replace('/', '-')}": {`);
      lines.push('  "type": "stdio",');
      lines.push(`  "command": "npx",`);
      lines.push(`  "args": ["-y", "${item.package}"]`);
      lines.push('}');
      lines.push('```');
      lines.push('');
    }
  }

  if (collected.vscode.length > 0) {
    lines.push('## Recommended VS Code Extensions', '');
    for (const item of collected.vscode) {
      lines.push(`- [\`${item.id}\`](https://marketplace.visualstudio.com/items?itemName=${item.id}) — for \`${item.trigger}\``);
    }
    lines.push('');
    lines.push('**Install all at once:**');
    lines.push('```bash');
    for (const item of collected.vscode) {
      lines.push(`code --install-extension ${item.id}`);
    }
    lines.push('```');
    lines.push('');
  }

  // Stack-specific skills first
  if (collected.skills.length > 0) {
    lines.push('## Agent Skills to Install', '');
    for (const item of collected.skills) {
      lines.push(`- **${item.name}** — for \`${item.trigger}\``);
    }
    lines.push('');
    lines.push('**Install via skills CLI** (source-based form `<source>@<skill>`):');
    lines.push('```bash');
    for (const item of collected.skills) {
      const spec = item.source ? `${item.source}@${item.name}` : `<source>@${item.name}`;
      lines.push(`npx -y skills add ${spec} -g -a github-copilot`);
    }
    lines.push('```');
    const unknownSources = collected.skills.filter(s => !s.source);
    if (unknownSources.length > 0) {
      lines.push('');
      lines.push(`> ⚠️  Skills without a known source (${unknownSources.map(s => `\`${s.name}\``).join(', ')}): find the GitHub repo hosting the skill and replace \`<source>\` before running.`);
    }
    lines.push('');
  }

  if (collected.copilotExtensions.length > 0) {
    lines.push('## GitHub Copilot Extensions', '');
    for (const item of collected.copilotExtensions) {
      lines.push(`- [${item.name}](${item.url}) — for \`${item.trigger}\``);
    }
    lines.push('');
  }

  // Plugin installs (Superpowers and any other harness-level plugin)
  if (collected.pluginInstalls.length > 0) {
    for (const plugin of collected.pluginInstalls) {
      lines.push(`## ${plugin.name}`, '');
      lines.push(`> ${plugin.description}`, '');

      // Note: AI OS repos already have these skills as local project copies
      if (plugin.skillSource) {
        lines.push('');
        lines.push('> **Note for AI OS repos:** If this repository has AI OS installed, the skills listed below are already available as project-local copies in `.github/copilot/skills/`.');
        lines.push('> Global install via the commands below is only needed for agents that do **not** read project-local skills (e.g. Cursor, Augment) or for cross-repo use.');
        lines.push('');
      }

      lines.push('**Install in your coding agent:**', '');
      lines.push('```bash');
      for (const step of plugin.steps) {
        lines.push(`# ${step.harness}`);
        lines.push(step.command);
        lines.push('');
      }
      lines.push('```');
      lines.push('');
      // Also show individual skills that belong to this plugin (matched by skillSource)
      const pluginSkills = plugin.skillSource
        ? collected.universalSkills.filter(s => s.source === plugin.skillSource)
        : [];
      if (pluginSkills.length > 0) {
        lines.push('**Or install individual skills via skills CLI:**', '');
        lines.push('```bash');
        for (const skill of pluginSkills) {
          lines.push(buildSkillsInstallCommand(skill));
        }
        lines.push('```');
        lines.push('');
      }
    }
  }

  // Universal/optional skills in a separate section (exclude skills already shown in plugin sections)
  const pluginSkillNames = new Set(
    collected.pluginInstalls.flatMap(plugin =>
      plugin.skillSource
        ? collected.universalSkills.filter(s => s.source === plugin.skillSource).map(s => s.name)
        : []
    )
  );
  const remainingUniversalSkills = collected.universalSkills.filter(s => !pluginSkillNames.has(s.name));

  if (remainingUniversalSkills.length > 0) {
    lines.push('## Universal Skills (Optional)', '');
    lines.push('> These skills are useful for any project and are not specific to the detected stack.');
    lines.push('');
    for (const item of remainingUniversalSkills) {
      lines.push(`- **${item.name}** — general purpose`);
    }
    lines.push('');
    lines.push('**Install via skills CLI** (source-based form `<source>@<skill>`):');
    lines.push('```bash');
    for (const item of remainingUniversalSkills) {
      lines.push(buildSkillsInstallCommand(item));
    }
    lines.push('```');
    const unknownSources = remainingUniversalSkills.filter(s => !s.source);
    if (unknownSources.length > 0) {
      lines.push('');
      lines.push(`> ⚠️  Skills without a known source (${unknownSources.map(s => `\`${s.name}\``).join(', ')}): find the GitHub repo hosting the skill and replace \`<source>\` before running.`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated at ${new Date().toISOString()} by AI OS*`);

  return lines.join('\n');
}

/** Generate the skills gap report (stdout message only). */
export function getSkillsGapReport(stack: DetectedStack, skillsLockPath: string, cwd?: string): string {
  const collected = collectRecommendations(stack);

  let installed: string[] = [];
  try {
    const lock = JSON.parse(fs.readFileSync(skillsLockPath, 'utf-8')) as {
      skills?: string[] | Record<string, unknown>;
    };
    // skills-lock.json may store skills as an array of names OR as an object keyed by skill name
    if (Array.isArray(lock.skills)) {
      installed = lock.skills;
    } else if (lock.skills && typeof lock.skills === 'object') {
      installed = Object.keys(lock.skills);
    }
  } catch {
    // skills-lock.json not present — treat all as missing
  }

  const installedSet = new Set(installed.map(s => s.toLowerCase()));

  // Also check disk for locally installed skills to avoid false positives (#247)
  if (cwd) {
    const canonicalSkillsDir = path.join(cwd, '.github', 'skills');
    if (fs.existsSync(canonicalSkillsDir)) {
      try {
        for (const entry of fs.readdirSync(canonicalSkillsDir, { withFileTypes: true })) {
          if (entry.isDirectory() && fs.existsSync(path.join(canonicalSkillsDir, entry.name, 'SKILL.md'))) {
            installedSet.add(entry.name.toLowerCase());
          }
        }
      } catch { /* ignore */ }
    }
    const legacySkillsDir = path.join(cwd, '.github', 'copilot', 'skills');
    if (fs.existsSync(legacySkillsDir)) {
      try {
        for (const file of fs.readdirSync(legacySkillsDir)) {
          if (file.endsWith('.md')) installedSet.add(file.replace(/\.md$/i, '').toLowerCase());
        }
      } catch { /* ignore */ }
    }
  }

  const missingStackItems = collected.skills.filter(s => !installedSet.has(s.name.toLowerCase()));
  const missingUniversalItems = collected.universalSkills.filter(s => !installedSet.has(s.name.toLowerCase()));
  const missingItems = [...missingStackItems, ...missingUniversalItems];

  if (missingItems.length === 0) return '';

  const cmds = missingItems.map(s => buildSkillsInstallCommand(s)).join('\n');
  return `  📦 Skills gap detected — Missing: [${missingItems.map(s => s.name).join(', ')}]\n  Run:\n${cmds.split('\n').map(l => `    ${l}`).join('\n')}`;
}

/** Generate recommendations.md and return its absolute path. */
export function generateRecommendations(stack: DetectedStack, outputDir: string): string {
  const collected = collectRecommendations(stack);
  const content = generateRecommendationsDoc(stack, collected);
  const outPath = path.join(outputDir, '.github', 'ai-os', 'recommendations.md');
  writeIfChanged(outPath, content);
  return outPath;
}

/** Return recommendations as a string for the MCP tool. */
export function buildRecommendationsText(stack: DetectedStack): string {
  const collected = collectRecommendations(stack);
  return generateRecommendationsDoc(stack, collected);
}
