import fs from 'node:fs';
import path from 'node:path';
import type { DetectedStack } from '../types.js';
import { writeIfChanged } from '../generators/utils.js';
import {
  DEPENDENCY_RECOMMENDATIONS,
  FRAMEWORK_RECOMMENDATIONS,
  LANGUAGE_RECOMMENDATIONS,
  UNIVERSAL_RECOMMENDATIONS,
  type StackRecommendation,
} from './registry.js';

interface CollectedRecommendations {
  mcp: Array<{ trigger: string; package: string; description: string }>;
  vscode: Array<{ trigger: string; id: string }>;
  skills: Array<{ trigger: string; name: string }>;
  copilotExtensions: Array<{ trigger: string; name: string; url: string }>;
}

export function collectRecommendations(stack: DetectedStack): CollectedRecommendations {
  const collected: CollectedRecommendations = { mcp: [], vscode: [], skills: [], copilotExtensions: [] };
  const seenMcp = new Set<string>();
  const seenVscode = new Set<string>();
  const seenSkills = new Set<string>();
  const seenExt = new Set<string>();

  function applyRec(rec: StackRecommendation): void {
    if (rec.mcp && !seenMcp.has(rec.mcp.package)) {
      seenMcp.add(rec.mcp.package);
      collected.mcp.push({ trigger: rec.trigger, package: rec.mcp.package, description: rec.mcp.description });
    }
    for (const ext of rec.vscode ?? []) {
      if (!seenVscode.has(ext)) {
        seenVscode.add(ext);
        collected.vscode.push({ trigger: rec.trigger, id: ext });
      }
    }
    for (const skill of rec.skills ?? []) {
      if (!seenSkills.has(skill)) {
        seenSkills.add(skill);
        collected.skills.push({ trigger: rec.trigger, name: skill });
      }
    }
    if (rec.copilotExtension && !seenExt.has(rec.copilotExtension.name)) {
      seenExt.add(rec.copilotExtension.name);
      collected.copilotExtensions.push({ trigger: rec.trigger, ...rec.copilotExtension });
    }
  }

  // Check dependencies
  for (const dep of stack.allDependencies) {
    const rec = DEPENDENCY_RECOMMENDATIONS[dep];
    if (rec) applyRec(rec);
  }

  // Check frameworks
  for (const fw of stack.frameworks) {
    const rec = FRAMEWORK_RECOMMENDATIONS[fw.name];
    if (rec) applyRec(rec);
  }

  // Check languages
  for (const lang of stack.languages) {
    const rec = LANGUAGE_RECOMMENDATIONS[lang.name];
    if (rec) applyRec(rec);
  }

  // Always apply universal recommendations
  for (const rec of UNIVERSAL_RECOMMENDATIONS) {
    applyRec(rec);
  }

  return collected;
}

function generateRecommendationsDoc(stack: DetectedStack, collected: CollectedRecommendations): string {
  const lines: string[] = [
    `# AI OS Recommendations — ${stack.projectName}`,
    '',
    '> Auto-generated by AI OS based on detected stack. Refreshed on every `--refresh-existing` run.',
    '',
  ];

  lines.push('## Lifecycle Orchestration (Define → Plan → Build → Verify → Review → Ship)', '');
  lines.push('AI OS embeds slash-command prompts for each lifecycle phase. Use them in order:');
  lines.push('');
  lines.push('| Phase | Prompt | Purpose |');
  lines.push('| ----- | ------ | ------- |');
  lines.push('| Define | `/define` | Structure feature intent, scope, constraints, and success criteria |');
  lines.push('| Plan | `/plan` | Break the feature into ordered, dependency-aware implementation tasks |');
  lines.push('| Build | `/build` | Execute one task at a time with minimal, convention-compliant changes |');
  lines.push('| Verify | `/verify` | Check implementation against success criteria and run tests |');
  lines.push('| Review | `/review` | Severity-tagged code review (Critical → Required → Optional → FYI) |');
  lines.push('| Ship | `/ship` | Pre-ship checklist — tests, secrets scan, changelog, version bump |');
  lines.push('');
  lines.push('> These prompts are available as VS Code Copilot slash commands via `.github/copilot/prompts.json`.');
  lines.push('');

  if (collected.mcp.length > 0) {
    lines.push('## Recommended MCP Servers', '');
    for (const item of collected.mcp) {
      lines.push(`### ${item.package}`);
      lines.push(`> Triggered by: \`${item.trigger}\``);
      lines.push('');
      lines.push(item.description);
      lines.push('');
      lines.push('**Install in `.vscode/mcp.json`:**');
      lines.push('```json');
      lines.push(`"${item.package.replace('/', '-')}": {`);
      lines.push('  "type": "stdio",');
      lines.push(`  "command": "npx",`);
      lines.push(`  "args": ["-y", "${item.package}"]`);
      lines.push('}');
      lines.push('```');
      lines.push('');
    }
  }

  if (collected.vscode.length > 0) {
    lines.push('## Recommended VS Code Extensions', '');
    for (const item of collected.vscode) {
      lines.push(`- [\`${item.id}\`](https://marketplace.visualstudio.com/items?itemName=${item.id}) — for \`${item.trigger}\``);
    }
    lines.push('');
    lines.push('**Install all at once:**');
    lines.push('```bash');
    for (const item of collected.vscode) {
      lines.push(`code --install-extension ${item.id}`);
    }
    lines.push('```');
    lines.push('');
  }

  if (collected.skills.length > 0) {
    lines.push('## Agent Skills to Install', '');
    for (const item of collected.skills) {
      lines.push(`- **${item.name}** — for \`${item.trigger}\``);
    }
    lines.push('');
    lines.push('**Install via skills CLI:**');
    lines.push('```bash');
    for (const item of collected.skills) {
      lines.push(`npx -y skills add --skill ${item.name} -g -a github-copilot`);
    }
    lines.push('```');
    lines.push('');
  }

  if (collected.copilotExtensions.length > 0) {
    lines.push('## GitHub Copilot Extensions', '');
    for (const item of collected.copilotExtensions) {
      lines.push(`- [${item.name}](${item.url}) — for \`${item.trigger}\``);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated at ${new Date().toISOString()} by AI OS*`);

  return lines.join('\n');
}

/** Generate the skills gap report (stdout message only). */
export function getSkillsGapReport(stack: DetectedStack, skillsLockPath: string): string {
  const collected = collectRecommendations(stack);
  const recommendedSkills = new Set(collected.skills.map(s => s.name));

  let installed: string[] = [];
  try {
    const lock = JSON.parse(fs.readFileSync(skillsLockPath, 'utf-8')) as {
      skills?: string[] | Record<string, unknown>;
    };
    // skills-lock.json may store skills as an array of names OR as an object keyed by skill name
    if (Array.isArray(lock.skills)) {
      installed = lock.skills;
    } else if (lock.skills && typeof lock.skills === 'object') {
      installed = Object.keys(lock.skills);
    }
  } catch {
    // skills-lock.json not present — treat all as missing
  }

  const installedSet = new Set(installed.map(s => s.toLowerCase()));
  const missing = [...recommendedSkills].filter(s => !installedSet.has(s.toLowerCase()));

  if (missing.length === 0) return '';

  const cmds = missing.map(s => `npx -y skills add --skill ${s} -g -a github-copilot`).join('\n');
  return `  📦 Skills gap detected — Missing: [${missing.join(', ')}]\n  Run:\n${cmds.split('\n').map(l => `    ${l}`).join('\n')}`;
}

/** Generate recommendations.md and return its absolute path. */
export function generateRecommendations(stack: DetectedStack, outputDir: string): string {
  const collected = collectRecommendations(stack);
  const content = generateRecommendationsDoc(stack, collected);
  const outPath = path.join(outputDir, '.github', 'ai-os', 'recommendations.md');
  writeIfChanged(outPath, content);
  return outPath;
}

/** Return recommendations as a string for the MCP tool. */
export function buildRecommendationsText(stack: DetectedStack): string {
  const collected = collectRecommendations(stack);
  return generateRecommendationsDoc(stack, collected);
}
