/**
 * Recommendation registry — maps detected stack signals to tool recommendations.
 * Each entry maps a dependency key, framework name, or language to a set of
 * recommended MCP servers, VS Code extensions, agent skills, and Copilot extensions.
 */

export interface StackRecommendation {
  /** What triggered this recommendation */
  trigger: string;
  /** Recommended MCP server (npm package or GitHub repo) */
  mcp?: { package: string; description: string };
  /** Recommended VS Code extension IDs */
  vscode?: string[];
  /** AI OS skills to install.
   * Each entry may include an optional `source` (GitHub `owner/repo`) for the
   * source-based CLI install form: `npx -y skills add <source>@<skill>`.
   * Skills without a source are generated by AI OS and do not need CLI installation. */
  skills?: Array<string | { name: string; source: string }>;
  /** GitHub Copilot Extension */
  copilotExtension?: { name: string; url: string };
}

/** Dependency key → recommendation */
export const DEPENDENCY_RECOMMENDATIONS: Record<string, StackRecommendation> = {
  prisma: {
    trigger: 'prisma',
    mcp: { package: 'prisma/mcp-server', description: 'Official Prisma MCP server for schema-aware DB queries' },
    vscode: ['Prisma.prisma'],
    skills: ['prisma'],
  },
  '@prisma/client': {
    trigger: '@prisma/client',
    mcp: { package: 'prisma/mcp-server', description: 'Official Prisma MCP server for schema-aware DB queries' },
    vscode: ['Prisma.prisma'],
    skills: ['prisma'],
  },
  stripe: {
    trigger: 'stripe',
    skills: ['stripe'],
    copilotExtension: { name: 'Stripe Copilot Extension', url: 'https://marketplace.visualstudio.com/items?itemName=Stripe.stripe-vscode' },
    vscode: ['Stripe.stripe-vscode'],
  },
  '@trpc/server': {
    trigger: '@trpc/server',
    skills: ['trpc'],
  },
  '@trpc/client': {
    trigger: '@trpc/client',
    skills: ['trpc'],
  },
  next: {
    trigger: 'next',
    skills: [
      'nextjs',
      { name: 'vercel-react-best-practices', source: 'vercel-labs/agent-skills' },
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
    vscode: ['bradlc.vscode-tailwindcss'],
  },
  'next.js': {
    trigger: 'next.js',
    skills: [
      'nextjs',
      { name: 'vercel-react-best-practices', source: 'vercel-labs/agent-skills' },
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
    vscode: ['bradlc.vscode-tailwindcss'],
  },
  react: {
    trigger: 'react',
    skills: [
      'react',
      { name: 'vercel-react-best-practices', source: 'vercel-labs/agent-skills' },
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
    vscode: ['dsznajder.es7-react-js-snippets', 'burkeholland.simple-react-snippets'],
  },
  nuxt: {
    trigger: 'nuxt',
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
    vscode: ['Vue.volar'],
  },
  vue: {
    trigger: 'vue',
    vscode: ['Vue.volar'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'express': {
    trigger: 'express',
    skills: ['express'],
  },
  'fastapi': {
    trigger: 'fastapi',
    skills: ['python-fastapi', { name: 'context7', source: 'intellectronica/agent-skills' }],
    vscode: ['ms-python.python'],
  },
  'django': {
    trigger: 'django',
    vscode: ['ms-python.python', 'batisteo.vscode-django'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  supabase: {
    trigger: 'supabase',
    mcp: { package: '@supabase/mcp-server-supabase', description: 'Official Supabase MCP server' },
    skills: ['supabase'],
    vscode: ['supabase.vscode-supabase-extension'],
  },
  '@supabase/supabase-js': {
    trigger: '@supabase/supabase-js',
    mcp: { package: '@supabase/mcp-server-supabase', description: 'Official Supabase MCP server' },
    skills: ['supabase'],
  },
  drizzle: {
    trigger: 'drizzle-orm',
    skills: ['prisma'], // drizzle uses similar patterns
  },
  'drizzle-orm': {
    trigger: 'drizzle-orm',
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
};

/** Framework name → recommendation */
export const FRAMEWORK_RECOMMENDATIONS: Record<string, StackRecommendation> = {
  'Next.js': {
    trigger: 'Next.js',
    skills: [
      'nextjs',
      { name: 'vercel-react-best-practices', source: 'vercel-labs/agent-skills' },
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
    vscode: ['dsznajder.es7-react-js-snippets', 'bradlc.vscode-tailwindcss'],
  },
  'React': {
    trigger: 'React',
    skills: [
      'react',
      { name: 'vercel-react-best-practices', source: 'vercel-labs/agent-skills' },
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
    vscode: ['dsznajder.es7-react-js-snippets'],
  },
  'Express': {
    trigger: 'Express',
    skills: ['express'],
  },
  'NestJS': {
    trigger: 'NestJS',
    vscode: ['nrwl.angular-console'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'FastAPI': {
    trigger: 'FastAPI',
    skills: ['python-fastapi', { name: 'context7', source: 'intellectronica/agent-skills' }],
    vscode: ['ms-python.python'],
  },
  'Spring Boot': {
    trigger: 'Spring Boot',
    skills: ['java-spring', { name: 'context7', source: 'intellectronica/agent-skills' }],
    vscode: ['vscjava.vscode-java-pack', 'redhat.java'],
  },
  'Astro': {
    trigger: 'Astro',
    vscode: ['astro-build.astro-vscode'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'SvelteKit': {
    trigger: 'SvelteKit',
    vscode: ['svelte.svelte-vscode'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Svelte': {
    trigger: 'Svelte',
    vscode: ['svelte.svelte-vscode'],
  },
  'Nuxt': {
    trigger: 'Nuxt',
    vscode: ['Vue.volar'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Vue': {
    trigger: 'Vue',
    vscode: ['Vue.volar'],
  },
  'tRPC': {
    trigger: 'tRPC',
    skills: ['trpc'],
  },
  'Prisma': {
    trigger: 'Prisma',
    mcp: { package: 'prisma/mcp-server', description: 'Official Prisma MCP server' },
    vscode: ['Prisma.prisma'],
    skills: ['prisma'],
  },
};

/** Language name → recommendation */
export const LANGUAGE_RECOMMENDATIONS: Record<string, StackRecommendation> = {
  'TypeScript': {
    trigger: 'TypeScript',
    vscode: ['ms-vscode.vscode-typescript-next'],
  },
  'Go': {
    trigger: 'Go',
    vscode: ['golang.go'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Rust': {
    trigger: 'Rust',
    vscode: ['rust-lang.rust-analyzer'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Python': {
    trigger: 'Python',
    vscode: ['ms-python.python', 'ms-python.black-formatter'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Java': {
    trigger: 'Java',
    vscode: ['vscjava.vscode-java-pack'],
    skills: [{ name: 'context7', source: 'intellectronica/agent-skills' }],
  },
  'Ruby': {
    trigger: 'Ruby',
    vscode: ['Shopify.ruby-lsp'],
  },
  'PHP': {
    trigger: 'PHP',
    vscode: ['bmewburn.vscode-intelephense-client'],
  },
};

/** Always-recommended universal tools */
export const UNIVERSAL_RECOMMENDATIONS: StackRecommendation[] = [
  {
    trigger: 'universal',
    skills: [
      'find-skills',
      { name: 'context7', source: 'intellectronica/agent-skills' },
    ],
  },
];
